### ISSUE TITLE
Re-generate client to make it compilable with 1.13 libraries

### ISSUE THREAD

**Issue by ash2k** [kubernetes/cluster-registry#271]
Please re-generate client, it currently does not work with 1.13 libraries.
Getting:
```console
vendor/k8s.io/cluster-registry/pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_cluster.go:135:44: not enough arguments in call to testing.NewPatchSubresourceAction
        have (schema.GroupVersionResource, string, string, []byte, []string...)
        want (schema.GroupVersionResource, string, string, types.PatchType, []byte, ...string)
```

/sig multicluster

**Comment by qiujian16** [comment]
meet the same issue

**Comment by hangyan** [comment]
same issue

**Comment by SleepyBrett** [comment]
same issue.

**Comment by glindsell** [comment]
Same issue

**Comment by zlcnju** [comment]
Same issue

**Comment by alebedev87** [comment]
It looks like in some point in time `kubebuilder` stopped generating clientset due to changes in `controller-runtime`, see the description of [this issue](https://github.com/kubernetes-sigs/kubebuilder/issues/403).

I tried to use `controller-runtime` go module and it worked well. I just needed to add `ClusterRegistry` scheme to the standard Kubernetes one:
```
import (
        "k8s.io/client-go/kubernetes/scheme"
	crapi "k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
)
...

func myFunc() {
	kubeCl, err := ctrlclient.New(kubeConfig, ctrlclient.Options{})
	if err != nil {
		return
	}
	
	crapi.AddToScheme(scheme.Scheme)

	clusters := &crapi.ClusterList{}
	err := kubeCl.List(context.TODO(), clusters)
	if err != nil {
        	return
	}

	for _, c := range clusters.Items {
		fmt.Println("Cluster:", c.Name)
	}
}
```

I hope this will be of help for those who are looking to use `ClusterRegistry` with recent `go` versions.

**Comment by nikhita** [comment]
Closing, this repo is being archived. Please see https://github.com/kubernetes/org/issues/1499 for more details.
